apiVersion: v1
kind: PersistentVolume
metadata:
 name: mysql-pv-volume
 labels:
  type: local
  app: Database
spec:
 storageClassName: Manual
 capacity: 
  storage: 1G
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pv-claim
spec:
 storageClassName: Manual
 accessModes:
  - ReadWriteOnce
 resources: 
  requests: 
   storage: 1G
   
 